# nixpacks.toml

[phases.setup]
nixPkgs = ["python311", "gcc", "curl"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --config gunicorn.conf.py api_server:create_app()"
