# File: nixpacks.toml
# Path: ./

[build]
builder = "nixpacks"

[start]
cmd = "gunicorn --config gunicorn.conf.py 'api_server:create_app'"


[variables]
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
FLASK_ENV = "production"
FLASK_DEBUG = "false"
FLASK_HOST = "0.0.0.0"
PORT = "8000"
WORKERS = "4"
WORKER_CLASS = "gevent"
WORKER_CONNECTIONS = "1000"
TIMEOUT = "120"
KEEPALIVE = "5"
MAX_REQUESTS = "1000"
MAX_REQUESTS_JITTER = "100"
ENABLE_METRICS = "true"
ENABLE_CACHING = "true"
CACHE_DURATION = "1800"
MAX_REQUESTS_PER_MINUTE = "60"
RATE_LIMIT_DEFAULT = "100 per hour"
LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
CACHE_TTL_CHANNEL = "1800"
CACHE_TTL_VIDEO = "600"
CACHE_TTL_RSS = "300"
DEFAULT_CACHE_TTL = "3600"
MIN_REQUEST_INTERVAL = "0.1"
MAX_RETRIES = "3"
RETRY_DELAY = "1.0"
MAX_VIDEO_BATCH_SIZE = "50"
MAX_CHANNEL_BATCH_SIZE = "50"
MAX_CONCURRENT_WORKERS = "5"
REQUIRE_API_AUTH = "true"
CORS_ORIGINS = "*"
REQUEST_TIMEOUT = "30"
NODE_ENV = "production"
DEBIAN_FRONTEND = "noninteractive"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python3 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip"
]

[phases.build]
cmds = [
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[checks]
startCommandHealthcheck = true
healthcheckPath = "/health"
healthcheckTimeout = 30
